#!/usr/bin/env python
import argparse
import logging
import os
from quelabrfid.serialcontrol import SerialControl


parser = argparse.ArgumentParser(description='Communicate with RFID Reader and Wild Apricot API')
parser.add_argument('device', default='/dev/ttyUSB0', help='The USB Serial Port of the Arduino')
parser.add_argument('-k', '--apikey', help='The USB Serial Port of the Arduino')
parser.add_argument('-c', '--cached', help='Cached Logins path, used when no network')
parser.add_argument('-m', '--mqtt_host', default='localhost', help='MQTT host to publish to')
parser.add_argument('-v', '--verbose',  action='store_true', help='verbose logging')
args = parser.parse_args()

if os.environ.get('WA_API_KEY'):
    key = os.environ.get('WA_API_KEY')
elif args.apikey:
    key = args.apikey
else:
    raise ValueError("No Wild Apricot Application API Key Given ENV: WA_API_KEY")

if args.verbose:
    level = logging.DEBUG
else:
    level = logging.INFO

controller = SerialControl(args.device, key, cached_logins=args.cached, mqtt_host=args.mqtt_host, log_level=level)
controller.run()
